{{- range $az := .Values.project.availabilityZones }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "abc"
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "sfs-gitops.labels" $ | nindent 4 }}
    operator.superphenix.net/managed: "true"
spec:
  project: {{ printf "spx-%s" $.Values.project.projectID | quote }}
  sources:
    - repoURL: {{ $.Values.project.gitops.manifestLocation.repoURL | quote }}
      path: {{ $.Values.project.gitops.manifestLocation.path | quote }}
      targetRevision: {{ $.Values.project.gitops.manifestLocation.targetRevision | default "HEAD" | quote }}
      helm:
        valueFiles:
          - $values/**/*.yaml
    - repoURL: {{ $.Values.project.gitops.valuesLocation.repoURL | quote }}
      targetRevision: {{ $.Values.project.gitops.valuesLocation.targetRevision | default "HEAD" | quote }}
      ref: values
  destination:
    name: {{ $az.cluster | quote }}
    namespace: {{ printf "spx-%s" $.Values.project.projectID | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
