apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.project.name | lower | replace " " "-" }}-gitops-info
  namespace: {{ .Release.Namespace }}
data:
  organizationName: {{ .Values.organization.name | quote }}
  projectName: {{ .Values.project.name | quote }}
  organizationID: {{ .Values.organization.organizationID | quote }}
  projectID: {{ .Values.project.projectID | quote }}
  availabilityZones: "{{ range $i, $az := .Values.project.availabilityZones }}{{ if $i }},{{ end }}{{ $az.name }}{{ end }}"
  products: "{{ range $i, $p := .Values.project.products }}{{ if $i }},{{ end }}{{ $p }}{{ end }}"
